[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.black]
line-length = "180"

[tool.pylint.format]
max-line-length = "180"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--import-mode=importlib", "-ra"]
markers = [
    "keras: marks keras fugu bricks",
    "keras_dense: marks keras fugu dense brick tests",
    "keras_pooling: marks keras fugu pooling brick tests",
    "keras_convolution: marks keras fugu convolution brick tests",
    "keras_convolution2: marks keras fugu (not 4d input) convolution brick tests",
    "whetstone: marks whetstone tests"
]
